# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Trust ngrok / reverse proxy
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    # Enable CSRF protection
    csrf_protection: true

    # Session configuration (FIXES invalid CSRF on ngrok HTTPS)
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file