_security_logout:
    resource: security.route_loader.logout
    type: service


api_controllers:
    resource: ../src/Controller/AuthController.php
    type: attribute

controllers:
    resource: ../src/Controller/
    type: attribute